stages: [lint]

variables:
  LUA_DIR: "addons/strategic_war_board/lua"

lint_swb:
  stage: lint
  image: alpine:3.20
  before_script:
    - apk add --no-cache lua5.4 lua5.4-dev luarocks git grep
    - luarocks install luacheck
  script:
    # 1) Lint syntaxe/style
    - luacheck $LUA_DIR

    # 2) Scan rapide anti-backdoor (basique, à raffiner)
    - echo "Scanning suspicious patterns..."
    - |
      SUSPICIOUS=$(grep -RniE "RunString|CompileString|setfenv|getfenv|loadstring|http\\.Fetch|file\\.Write|file\\.Open\\(\".*data|net\\.Receive\\(\".*\"\\)" $LUA_DIR || true)
      if [ -n "$SUSPICIOUS" ]; then
        echo "Potentially dangerous patterns found:"
        echo "$SUSPICIOUS"
        # On n'échoue pas encore le job pour éviter les faux-positifs au tout début.
        # exit 1
      else
        echo "No suspicious patterns found."
      fi
  only:
    - branches
    - merge_requests
